jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nvcr.io/nvidia/hpc-sdk:25.5-cuda11.8
    steps:
      - uses: actions/checkout@v3
      - name: Show nvc++ version
        run: nvc++ --version
      - name: Build
        run: make